//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodWorkersMVP.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoodWorkersMVP.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About me.
        /// </summary>
        public static string AboutMeLabel {
            get {
                return ResourceManager.GetString("AboutMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tell me about you.
        /// </summary>
        public static string AboutMePlaceholder {
            get {
                return ResourceManager.GetString("AboutMePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About me field cannot be empty.
        /// </summary>
        public static string AboutMeValidationEmpty {
            get {
                return ResourceManager.GetString("AboutMeValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address cannot be empty.
        /// </summary>
        public static string AddressValidationEmpty {
            get {
                return ResourceManager.GetString("AddressValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Birth date.
        /// </summary>
        public static string BirthdateLabel {
            get {
                return ResourceManager.GetString("BirthdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string BtnAcceptDialog {
            get {
                return ResourceManager.GetString("BtnAcceptDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string BtnCancelDialog {
            get {
                return ResourceManager.GetString("BtnCancelDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string BtnEnterLabel {
            get {
                return ResourceManager.GetString("BtnEnterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register User.
        /// </summary>
        public static string BtnRegisterLabel {
            get {
                return ResourceManager.GetString("BtnRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell phone.
        /// </summary>
        public static string CellPhoneLabel {
            get {
                return ResourceManager.GetString("CellPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellphone cannot be empty.
        /// </summary>
        public static string CellphoneValidationEmpty {
            get {
                return ResourceManager.GetString("CellphoneValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tap here for change a image profile.
        /// </summary>
        public static string ChangeImageProfileLabel {
            get {
                return ResourceManager.GetString("ChangeImageProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confrim password.
        /// </summary>
        public static string ConfirmedPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmedPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document Number.
        /// </summary>
        public static string DocumentNumberLabel {
            get {
                return ResourceManager.GetString("DocumentNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document number cannot be empty.
        /// </summary>
        public static string DocumentNumberValidationEmpty {
            get {
                return ResourceManager.GetString("DocumentNumberValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document Type.
        /// </summary>
        public static string DocumentTypeLabel {
            get {
                return ResourceManager.GetString("DocumentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Address.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your Email Address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter an Email Address.
        /// </summary>
        public static string ErrorEmailEmptyLabel {
            get {
                return ResourceManager.GetString("ErrorEmailEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a valid Email Address.
        /// </summary>
        public static string ErrorEmailInvalidLabel {
            get {
                return ResourceManager.GetString("ErrorEmailInvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a Password.
        /// </summary>
        public static string ErrorPasswordEmptyLabel {
            get {
                return ResourceManager.GetString("ErrorPasswordEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitleDialog {
            get {
                return ResourceManager.GetString("ErrorTitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First name cannot be empty.
        /// </summary>
        public static string FirstNameValidationEmpty {
            get {
                return ResourceManager.GetString("FirstNameValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string ForgetPasswordLabel {
            get {
                return ResourceManager.GetString("ForgetPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name cannot be empty.
        /// </summary>
        public static string LastNameValidationEmpty {
            get {
                return ResourceManager.GetString("LastNameValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string LoginTitlePage {
            get {
                return ResourceManager.GetString("LoginTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, enable your internet connection.
        /// </summary>
        public static string NoInternetDialog {
            get {
                return ResourceManager.GetString("NoInternetDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please check your internet connection.
        /// </summary>
        public static string NoIntertnetWorkingDialog {
            get {
                return ResourceManager.GetString("NoIntertnetWorkingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupation.
        /// </summary>
        public static string OcupationLabel {
            get {
                return ResourceManager.GetString("OcupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a These passwords dosen&apos;t match, please check .
        /// </summary>
        public static string PasswordValidationConfirm {
            get {
                return ResourceManager.GetString("PasswordValidationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This password is not valid, please check.
        /// </summary>
        public static string PasswordValidationCorrect {
            get {
                return ResourceManager.GetString("PasswordValidationCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can login now.
        /// </summary>
        public static string RegisterConfirmationMessage {
            get {
                return ResourceManager.GetString("RegisterConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully Registered.
        /// </summary>
        public static string RegisterConfirmationTitleDialog {
            get {
                return ResourceManager.GetString("RegisterConfirmationTitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string RegisterEmailLabel {
            get {
                return ResourceManager.GetString("RegisterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string RegisterFirstName {
            get {
                return ResourceManager.GetString("RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string RegisterLastName {
            get {
                return ResourceManager.GetString("RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Middle Name.
        /// </summary>
        public static string RegisterMiddleName {
            get {
                return ResourceManager.GetString("RegisterMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string RegisterPasswordLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string RegisterTitlePage {
            get {
                return ResourceManager.GetString("RegisterTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember my data?.
        /// </summary>
        public static string RememberMyDataLabel {
            get {
                return ResourceManager.GetString("RememberMyDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string SearchPLaceholderInput {
            get {
                return ResourceManager.GetString("SearchPLaceholderInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Country.
        /// </summary>
        public static string SelectCountryPlaceHolder {
            get {
                return ResourceManager.GetString("SelectCountryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select user type.
        /// </summary>
        public static string SelectDocumentTypeLabel {
            get {
                return ResourceManager.GetString("SelectDocumentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Ocupation.
        /// </summary>
        public static string SelectOcupationLabel {
            get {
                return ResourceManager.GetString("SelectOcupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select City.
        /// </summary>
        public static string SelectStateProvincePlaceholder {
            get {
                return ResourceManager.GetString("SelectStateProvincePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string StateProvinceLabel {
            get {
                return ResourceManager.GetString("StateProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terms and conditions.
        /// </summary>
        public static string TermAndConditionsLabel {
            get {
                return ResourceManager.GetString("TermAndConditionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to detect locations.
        /// </summary>
        public static string UnableLocation {
            get {
                return ResourceManager.GetString("UnableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Type.
        /// </summary>
        public static string UserTypeTitleRegister {
            get {
                return ResourceManager.GetString("UserTypeTitleRegister", resourceCulture);
            }
        }
    }
}
