//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodWorkersMVP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoodWorkersMVP.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        public static string AboutMeLabel {
            get {
                return ResourceManager.GetString("AboutMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me about you.
        /// </summary>
        public static string AboutMePlaceholder {
            get {
                return ResourceManager.GetString("AboutMePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me field cannot be empty.
        /// </summary>
        public static string AboutMeValidationEmpty {
            get {
                return ResourceManager.GetString("AboutMeValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be empty.
        /// </summary>
        public static string AddressValidationEmpty {
            get {
                return ResourceManager.GetString("AddressValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthdateLabel {
            get {
                return ResourceManager.GetString("BirthdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string BtnAcceptDialog {
            get {
                return ResourceManager.GetString("BtnAcceptDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancelDialog {
            get {
                return ResourceManager.GetString("BtnCancelDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BtnEnterLabel {
            get {
                return ResourceManager.GetString("BtnEnterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register User.
        /// </summary>
        public static string BtnRegisterLabel {
            get {
                return ResourceManager.GetString("BtnRegisterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string CellPhoneLabel {
            get {
                return ResourceManager.GetString("CellPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellphone cannot be empty.
        /// </summary>
        public static string CellphoneValidationEmpty {
            get {
                return ResourceManager.GetString("CellphoneValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here for change a image profile.
        /// </summary>
        public static string ChangeImageProfileLabel {
            get {
                return ResourceManager.GetString("ChangeImageProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confrim password.
        /// </summary>
        public static string ConfirmedPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmedPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Number.
        /// </summary>
        public static string DocumentNumberLabel {
            get {
                return ResourceManager.GetString("DocumentNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number cannot be empty.
        /// </summary>
        public static string DocumentNumberValidationEmpty {
            get {
                return ResourceManager.GetString("DocumentNumberValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentTypeLabel {
            get {
                return ResourceManager.GetString("DocumentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Email Address.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid email.
        /// </summary>
        public static string EmailValidationCorrect {
            get {
                return ResourceManager.GetString("EmailValidationCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an Email Address.
        /// </summary>
        public static string ErrorEmailEmptyLabel {
            get {
                return ResourceManager.GetString("ErrorEmailEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid Email Address.
        /// </summary>
        public static string ErrorEmailInvalidLabel {
            get {
                return ResourceManager.GetString("ErrorEmailInvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a Password.
        /// </summary>
        public static string ErrorPasswordEmptyLabel {
            get {
                return ResourceManager.GetString("ErrorPasswordEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitleDialog {
            get {
                return ResourceManager.GetString("ErrorTitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty.
        /// </summary>
        public static string FirstNameValidationEmpty {
            get {
                return ResourceManager.GetString("FirstNameValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgetPasswordLabel {
            get {
                return ResourceManager.GetString("ForgetPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty.
        /// </summary>
        public static string LastNameValidationEmpty {
            get {
                return ResourceManager.GetString("LastNameValidationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LoginTitlePage {
            get {
                return ResourceManager.GetString("LoginTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enable your internet connection.
        /// </summary>
        public static string NoInternetDialog {
            get {
                return ResourceManager.GetString("NoInternetDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection.
        /// </summary>
        public static string NoIntertnetWorkingDialog {
            get {
                return ResourceManager.GetString("NoIntertnetWorkingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupation.
        /// </summary>
        public static string OcupationLabel {
            get {
                return ResourceManager.GetString("OcupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These passwords dosen&apos;t match, please check .
        /// </summary>
        public static string PasswordValidationConfirm {
            get {
                return ResourceManager.GetString("PasswordValidationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password is not valid, please check.
        /// </summary>
        public static string PasswordValidationCorrect {
            get {
                return ResourceManager.GetString("PasswordValidationCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterBtn {
            get {
                return ResourceManager.GetString("RegisterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can login now.
        /// </summary>
        public static string RegisterConfirmationMessage {
            get {
                return ResourceManager.GetString("RegisterConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Registered.
        /// </summary>
        public static string RegisterConfirmationTitleDialog {
            get {
                return ResourceManager.GetString("RegisterConfirmationTitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmailLabel {
            get {
                return ResourceManager.GetString("RegisterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string RegisterFirstName {
            get {
                return ResourceManager.GetString("RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string RegisterLastName {
            get {
                return ResourceManager.GetString("RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string RegisterMiddleName {
            get {
                return ResourceManager.GetString("RegisterMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPasswordLabel {
            get {
                return ResourceManager.GetString("RegisterPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string RegisterTitlePage {
            get {
                return ResourceManager.GetString("RegisterTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my data?.
        /// </summary>
        public static string RememberMyDataLabel {
            get {
                return ResourceManager.GetString("RememberMyDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPLaceholderInput {
            get {
                return ResourceManager.GetString("SearchPLaceholderInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountryPlaceHolder {
            get {
                return ResourceManager.GetString("SelectCountryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user type.
        /// </summary>
        public static string SelectDocumentTypeLabel {
            get {
                return ResourceManager.GetString("SelectDocumentTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ocupation.
        /// </summary>
        public static string SelectOcupationLabel {
            get {
                return ResourceManager.GetString("SelectOcupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string SelectStateProvincePlaceholder {
            get {
                return ResourceManager.GetString("SelectStateProvincePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string StateProvinceLabel {
            get {
                return ResourceManager.GetString("StateProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string TakePicDialogCamera {
            get {
                return ResourceManager.GetString("TakePicDialogCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string TakePicDialogGallery {
            get {
                return ResourceManager.GetString("TakePicDialogGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take image from.
        /// </summary>
        public static string TakePickFrom {
            get {
                return ResourceManager.GetString("TakePickFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermAndConditionsLabel {
            get {
                return ResourceManager.GetString("TermAndConditionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect locations.
        /// </summary>
        public static string UnableLocation {
            get {
                return ResourceManager.GetString("UnableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserTypeTitleRegister {
            get {
                return ResourceManager.GetString("UserTypeTitleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        public static string ValidationEmailEmptyMessage {
            get {
                return ResourceManager.GetString("ValidationEmailEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string ValidationPasswordEmpty {
            get {
                return ResourceManager.GetString("ValidationPasswordEmpty", resourceCulture);
            }
        }
    }
}
