<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
    <TargetFrameworks>net8.0-ios</TargetFrameworks>
    <UseMaui>True</UseMaui>
    <AssemblyTitle>GoodWorkersMVP.iOS</AssemblyTitle>
    <Product>GoodWorkersMVP.iOS</Product>
    <Copyright>Copyright ©  2014</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    <ConsolePause>false</ConsolePause>
    <MtouchLink>None</MtouchLink>
    <MtouchDebug>true</MtouchDebug>
    <RuntimeIdentifiers>iossimulator-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">
    <MtouchLink>None</MtouchLink>
    <ConsolePause>false</ConsolePause>
    <RuntimeIdentifiers>iossimulator-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
    <MtouchDebug>true</MtouchDebug>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Ad-Hoc|iPhone' ">
    <ConsolePause>False</ConsolePause>
    <BuildIpa>True</BuildIpa>
    <CodesignProvision>Automatic:AdHoc</CodesignProvision>
    <CodesignKey>iPhone Distribution</CodesignKey>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'AppStore|iPhone' ">
    <ConsolePause>False</ConsolePause>
    <CodesignProvision>Automatic:AppStore</CodesignProvision>
    <CodesignKey>iPhone Distribution</CodesignKey>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <RuntimeIdentifiers>ios-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Xam.Plugin.Media">
      <Version>6.0.2</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GoodWorkersMVP\GoodWorkersMVP.csproj" />
  </ItemGroup>
</Project>